name: Autodeploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Set Node.js version to 16

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Set Git User Information
        run: |
          git config --global user.name "vadym4che"
          git config --global user.email "vadym4che@gmail.com"
        shell: bash

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          npm run autodeploy
