name: Vue app Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Set Node.js version to 16

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Set Git User Information
        run: |
          git config --global user.name "vadym4che"
          git config --global user.email "vadym4che@gmail.com"

      - name: Build and Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          npm install -g gh-pages
          gh-pages -d dist -b gh-pages -u "$GH_TOKEN"
